name = "ordini-elly-worker"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[[d1_databases]]
binding = "DB"
database_name = "ordini-elly-db"
database_id = "9f76e4ad-2874-438d-bf2e-0f4185b44aeb"

[[r2_buckets]]
binding = "RELEASES"
bucket_name = "ordini-releases"

# In produzione, imposta JWT_SECRET come secret:
# npx wrangler secret put JWT_SECRET
